export const DISHES = [
  {
    id: 0,
    name: "Uthappizza",
    image: "/assests/images/buffet.png",
    category: "mains",
    label: "Hot",
    serving: "2",
    day: "monday",
    price: "400",
    featured: true,
    description:
      "A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.",
  },
  {
    id: 1,
    name: "Zucchipakoda",
    image: "/assests/images/zucchipakoda.png",
    category: "appetizer",
    label: "",
    serving: "3",
    day: "monday",
    price: "1000",
    featured: false,
    description:
      "Deep fried Zucchini coated with mildly spiced Chickpea flour batter accompanied with a sweet-tangy tamarind sauce",
  },
  {
    id: 2,
    name: "Vadonut",
    image: "/assests/images/vadonut.png",
    category: "appetizer",
    label: "New",
    serving: "2",
    day: "monday",
    price: "800",
    featured: false,
    description:
      "A quintessential ConFusion experience, is it a vada or is it a donut?",
  },
  {
    id: 3,
    name: "ElaiCheese Cake",
    image: "/assests/images/elaicheesecake.png",
    category: "dessert",
    label: "",
    serving: "4",
    day: "monday",
    price: "1200",
    featured: false,
    description:
      "A delectable, semi-sweet New York Style Cheese Cake, with Graham cracker crust and spiced with Indian cardamoms",
  },
  {
    id: 4,
    name: "Beef",
    image: "/assests/images/burger (4).jpg",
    category: "regualr",
    label: "New",
    serving: "4",
    day: "monday",
    price: "1800",
    featured: false,
    description:
      "A quintessential ConFusion experience, is it a vada or is it a donut?",
  },
  {
    id: 5,
    name: "Chicken",
    image: "/assests/images/veg2.jpg",
    category: "regualr",
    label: "New",
    serving: "1",
    day: "monday",
    price: "108",
    featured: false,
    description:
      "A quintessential ConFusion experience, is it a vada or is it a donut?",
  },
  {
    id: 6,
    name: "Steak",
    image: "/assests/images/steak.jpg",
    category: "regualr",
    label: "New",
    serving: "1",
    day: "monday",
    price: "1200",
    featured: false,
    description:
      "A quintessential ConFusion experience, is it a vada or is it a donut?",
  },
  {
    id: 7,
    name: "Rice",
    image: "/assests/images/rice.jpg",
    category: "regualr",
    label: "New",
    serving: "2",
    day: "monday",
    price: "300",
    featured: false,
    description:
      "A quintessential ConFusion experience, is it a vada or is it a donut?",
  },
  {
    id: 8,
    name: "burger",
    image: "/assests/images/burger.jpg",
    category: "regualr",
    label: "New",
    serving: "1",
    day: "monday",
    price: "800",
    featured: false,
    description:
      "A quintessential ConFusion experience, is it a vada or is it a donut?",
  },
  {
    id: 9,
    name: "salad",
    image: "/assests/images/salad.jpg",
    category: "regualr",
    label: "New",
    serving: "1",
    day: "monday",
    price: "600",
    featured: false,
    description:
      "A quintessential ConFusion experience, is it a vada or is it a donut?",
  },
];
export default DISHES;
